{{- range .Values.configs }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "docker-hub-rate-limit-exporter.fullname" $ }}-{{ .name }}
  labels:
    {{- include "docker-hub-rate-limit-exporter.labels" $ | nindent 4 }}
    instance: {{ .name }}
spec:
  type: {{ $.Values.service.type }}
  ports:
    - port: {{ $.Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "docker-hub-rate-limit-exporter.selectorLabels" $ | nindent 4 }}
    instance: {{ .name }}
{{- end }}
